package emit

import (
	"fmt"
	"slices"
	"strings"

	"github.com/ivov/lisette/bindgen/internal/config"
	"github.com/ivov/lisette/bindgen/internal/convert"
	"github.com/ivov/lisette/bindgen/internal/extract"
)

type stats struct {
	functions int
	methods   int
	types     int
	constants int
	variables int
}

type Emitter struct {
	buf     strings.Builder
	stats   stats
	skipped int
	methods map[string][]convert.ConvertResult // receiver type name -> methods
	cfg     *config.Config
	pkgPath string
}

func NewEmitter(cfg *config.Config, pkgPath string) *Emitter {
	return &Emitter{
		methods: make(map[string][]convert.ConvertResult),
		cfg:     cfg,
		pkgPath: pkgPath,
	}
}

func (e *Emitter) EmitHeader(pkg, pkgName, lisetteVersion, goVersion string) {
	e.buf.WriteString("// Generated by Lisette bindgen\n")
	fmt.Fprintf(&e.buf, "// Source: %s (%s)\n", pkg, packageSourceType(pkg))
	if lastSegment := pkg[strings.LastIndex(pkg, "/")+1:]; pkgName != lastSegment {
		fmt.Fprintf(&e.buf, "// Package: %s\n", pkgName)
	}
	fmt.Fprintf(&e.buf, "// Go: %s\n", strings.TrimPrefix(goVersion, "go"))
	fmt.Fprintf(&e.buf, "// Lisette: %s\n", lisetteVersion)
	e.buf.WriteString("\n")
}

func packageSourceType(pkg string) string {
	if strings.HasPrefix(pkg, "/") || strings.HasPrefix(pkg, "./") || strings.HasPrefix(pkg, "../") {
		return "local"
	}

	if strings.HasPrefix(pkg, "golang.org/x/") {
		return "Go extended"
	}

	firstSegment := pkg
	if idx := strings.Index(pkg, "/"); idx != -1 {
		firstSegment = pkg[:idx]
	}

	if strings.Contains(firstSegment, ".") {
		return "Go community"
	}

	return "Go stdlib"
}

func (e *Emitter) EmitImports(externalPkgs convert.ExternalPkgs) {
	if len(externalPkgs) == 0 {
		return
	}

	paths := make([]string, 0, len(externalPkgs))
	for path := range externalPkgs {
		paths = append(paths, path)
	}
	slices.Sort(paths)

	for _, path := range paths {
		fmt.Fprintf(&e.buf, "import \"go:%s\"\n", path)
	}

	e.buf.WriteString("\n")
}

func (e *Emitter) EmitExport(result convert.ConvertResult) {
	switch result.Kind {
	case extract.ExportFunction:
		e.emitFunction(result)
		e.stats.functions++
	case extract.ExportMethod:
		if e.collectMethod(result) {
			e.stats.methods++
		}
	case extract.ExportType:
		e.emitType(result)
		e.stats.types++
	case extract.ExportConstant:
		e.emitConst(result)
		e.stats.constants++
	case extract.ExportVariable:
		e.emitVariable(result)
		e.stats.variables++
	}
}

func (e *Emitter) collectMethod(result convert.ConvertResult) bool {
	if result.Receiver == nil {
		return false
	}

	baseTypeName := result.Receiver.BaseTypeName
	if baseTypeName == "" {
		return false
	}

	e.methods[baseTypeName] = append(e.methods[baseTypeName], result)
	return true
}

func (e *Emitter) EmitUnloadableNote(firstError string) {
	e.buf.WriteString("// Status: UNLOADABLE — package could not be type-checked on this host\n")
	fmt.Fprintf(&e.buf, "// First error: %s\n", firstError)
	e.buf.WriteString("\n")
}

func (e *Emitter) EmitSkipped(name string, reason *convert.SkipReason) {
	fmt.Fprintf(&e.buf, "// SKIPPED: %s - %s\n", name, reason.Code)
	fmt.Fprintf(&e.buf, "// %s\n", reason.Message)

	if reason.EmitOpaqueType {
		fmt.Fprintf(&e.buf, "pub type %s\n", name)
		e.stats.types++
	}

	e.buf.WriteString("\n")
	e.skipped++
}

func (e *Emitter) EmitImplBlocks() {
	if len(e.methods) == 0 {
		return
	}

	typeNames := make([]string, 0, len(e.methods))
	for typeName := range e.methods {
		typeNames = append(typeNames, typeName)
	}
	slices.Sort(typeNames)

	for _, typeName := range typeNames {
		methods := e.methods[typeName]
		if len(methods) == 0 {
			continue
		}

		var typeParams []string
		if methods[0].Receiver != nil {
			typeParams = methods[0].Receiver.TypeParams
		}

		if len(typeParams) > 0 {
			typeParamList := strings.Join(typeParams, ", ")
			fmt.Fprintf(&e.buf, "impl<%s> %s<%s> {\n", typeParamList, typeName, typeParamList)
		} else {
			fmt.Fprintf(&e.buf, "impl %s {\n", typeName)
		}
		for _, method := range methods {
			e.emitMethodInImpl(method)
		}

		e.buf.WriteString("}\n\n")
	}
}

func (e *Emitter) Summary() string {
	var buf strings.Builder
	total := e.stats.functions + e.stats.methods + e.stats.types + e.stats.constants + e.stats.variables
	fmt.Fprintf(&buf, "Generated: %d functions, %d methods, %d types, %d constants, %d variables\n",
		e.stats.functions, e.stats.methods, e.stats.types, e.stats.constants, e.stats.variables)
	fmt.Fprintf(&buf, "Total: %d symbols\n", total)
	if e.skipped > 0 {
		fmt.Fprintf(&buf, "Skipped: %d symbols\n", e.skipped)
	}
	return buf.String()
}

func (e *Emitter) String() string {
	return strings.TrimRight(e.buf.String(), "\n") + "\n"
}

func (e *Emitter) emitFunction(result convert.ConvertResult) {
	e.emitDocWithIndent(result.Doc, "")

	if result.CommaOk {
		e.buf.WriteString("#[go(comma_ok)]\n")
	}
	if result.ArrayReturn {
		e.buf.WriteString("#[go(array_return)]\n")
	}
	if e.shouldAllowUnusedResult(result.Name, "", result) {
		e.buf.WriteString("#[allow(unused_result)]\n")
	}

	var functionSignature strings.Builder
	functionSignature.WriteString("pub fn ")
	functionSignature.WriteString(result.Name)

	if len(result.TypeParams) > 0 {
		functionSignature.WriteString("<")
		functionSignature.WriteString(strings.Join(result.TypeParams, ", "))
		functionSignature.WriteString(">")
	}

	functionSignature.WriteString("(")
	var params []string
	for _, p := range result.Params {
		if p.Mutable {
			params = append(params, fmt.Sprintf("mut %s: %s", p.Name, p.Type))
		} else {
			params = append(params, fmt.Sprintf("%s: %s", p.Name, p.Type))
		}
	}
	functionSignature.WriteString(strings.Join(params, ", "))
	functionSignature.WriteString(")")

	if result.ReturnType != "" && result.ReturnType != "()" {
		functionSignature.WriteString(" -> ")
		functionSignature.WriteString(result.ReturnType)
	}

	e.buf.WriteString(functionSignature.String())
	e.buf.WriteString("\n\n")
}

// shouldAllowUnusedResult returns true if the function/method should be annotated
// with #[allow(unused_result)]. Checks config first, then applies signature-based
// heuristics for common Go interface methods:
//   - Close() error
//   - Flush() error
//   - Write([]byte) (int, error)  [io.Writer signature]
func (e *Emitter) shouldAllowUnusedResult(qualifiedName, methodName string, result convert.ConvertResult) bool {
	if e.cfg != nil && e.cfg.ShouldAllowUnusedResult(e.pkgPath, qualifiedName) {
		return true
	}

	name := methodName
	if name == "" {
		name = result.Name
	}

	switch name {
	case "Close", "Flush":
		return len(result.Params) == 0 && result.ReturnType == "Result<(), error>"
	case "Write":
		return len(result.Params) == 1 && result.Params[0].Type == "Slice<uint8>" &&
			result.ReturnType == "Result<int, error>"
	}

	return false
}

func (e *Emitter) emitMethodInImpl(result convert.ConvertResult) {
	e.emitDocWithIndent(result.Doc, "  ")

	if result.CommaOk {
		e.buf.WriteString("  #[go(comma_ok)]\n")
	}
	if result.ArrayReturn {
		e.buf.WriteString("  #[go(array_return)]\n")
	}
	if result.Receiver != nil {
		qualifiedName := result.Receiver.BaseTypeName + "." + result.Name
		if e.shouldAllowUnusedResult(qualifiedName, result.Name, result) {
			e.buf.WriteString("  #[allow(unused_result)]\n")
		}
	}

	var methodSignature strings.Builder
	methodSignature.WriteString("  fn ")
	methodSignature.WriteString(result.Name)

	if len(result.TypeParams) > 0 {
		methodSignature.WriteString("<")
		methodSignature.WriteString(strings.Join(result.TypeParams, ", "))
		methodSignature.WriteString(">")
	}

	methodSignature.WriteString("(")
	var params []string
	if result.Receiver != nil && result.Receiver.IsPointer {
		typeName := result.Receiver.BaseTypeName
		if len(result.Receiver.TypeParams) > 0 {
			typeName += "<" + strings.Join(result.Receiver.TypeParams, ", ") + ">"
		}
		params = append(params, fmt.Sprintf("self: Ref<%s>", typeName))
	} else {
		params = append(params, "self")
	}

	for _, p := range result.Params {
		if p.Mutable {
			params = append(params, fmt.Sprintf("mut %s: %s", p.Name, p.Type))
		} else {
			params = append(params, fmt.Sprintf("%s: %s", p.Name, p.Type))
		}
	}

	methodSignature.WriteString(strings.Join(params, ", "))
	methodSignature.WriteString(")")

	if result.ReturnType != "" && result.ReturnType != "()" {
		methodSignature.WriteString(" -> ")
		methodSignature.WriteString(result.ReturnType)
	}

	e.buf.WriteString(methodSignature.String())
	e.buf.WriteString("\n")
}

func (e *Emitter) emitType(result convert.ConvertResult) {
	e.emitDocWithIndent(result.Doc, "")

	typeName := result.Name

	if len(result.InterfaceMethods) > 0 {
		var signature strings.Builder
		signature.WriteString("pub interface ")
		signature.WriteString(typeName)

		if len(result.TypeParams) > 0 {
			signature.WriteString("<")
			signature.WriteString(strings.Join(result.TypeParams, ", "))
			signature.WriteString(">")
		}

		signature.WriteString(" {\n")
		for _, m := range result.InterfaceMethods {
			if m.CommaOk {
				signature.WriteString("  #[go(comma_ok)]\n")
			}
			if m.ArrayReturn {
				signature.WriteString("  #[go(array_return)]\n")
			}
			signature.WriteString("  fn ")
			signature.WriteString(m.Name)
			signature.WriteString("(")

			var params []string
			for _, p := range m.Params {
				if p.Mutable {
					params = append(params, fmt.Sprintf("mut %s: %s", p.Name, p.Type))
				} else {
					params = append(params, fmt.Sprintf("%s: %s", p.Name, p.Type))
				}
			}
			signature.WriteString(strings.Join(params, ", "))
			signature.WriteString(")")

			if m.ReturnType != "" && m.ReturnType != "()" {
				signature.WriteString(" -> ")
				signature.WriteString(m.ReturnType)
			}
			signature.WriteString("\n")
		}
		signature.WriteString("}")

		e.buf.WriteString(signature.String())
		e.buf.WriteString("\n\n")
		return
	}

	if len(result.Fields) > 0 {
		var sig strings.Builder
		sig.WriteString("pub struct ")
		sig.WriteString(typeName)

		if len(result.TypeParams) > 0 {
			sig.WriteString("<")
			sig.WriteString(strings.Join(result.TypeParams, ", "))
			sig.WriteString(">")
		}

		sig.WriteString(" {\n")
		for _, f := range result.Fields {
			if f.Doc != "" {
				for line := range strings.SplitSeq(f.Doc, "\n") {
					sig.WriteString("  /// ")
					sig.WriteString(line)
					sig.WriteString("\n")
				}
			}
			sig.WriteString("  pub ")
			sig.WriteString(f.Name)
			sig.WriteString(": ")
			sig.WriteString(f.Type)
			sig.WriteString(",\n")
		}
		sig.WriteString("}")

		e.buf.WriteString(sig.String())
		e.buf.WriteString("\n\n")
		return
	}

	if result.LisetteType != "" {
		var sig strings.Builder

		if strings.HasPrefix(result.LisetteType, "fn(") || result.IsTypeAlias {
			sig.WriteString("pub type ")
			sig.WriteString(typeName)

			if len(result.TypeParams) > 0 {
				sig.WriteString("<")
				sig.WriteString(strings.Join(result.TypeParams, ", "))
				sig.WriteString(">")
			}

			sig.WriteString(" = ")
			sig.WriteString(result.LisetteType)
		} else {
			sig.WriteString("pub struct ")
			sig.WriteString(typeName)

			if len(result.TypeParams) > 0 {
				sig.WriteString("<")
				sig.WriteString(strings.Join(result.TypeParams, ", "))
				sig.WriteString(">")
			}

			sig.WriteString("(")
			sig.WriteString(result.LisetteType)
			sig.WriteString(")")
		}

		e.buf.WriteString(sig.String())
		e.buf.WriteString("\n\n")
		return
	}

	var signature strings.Builder
	signature.WriteString("pub type ")
	signature.WriteString(typeName)

	if len(result.TypeParams) > 0 {
		signature.WriteString("<")
		signature.WriteString(strings.Join(result.TypeParams, ", "))
		signature.WriteString(">")
	}

	e.buf.WriteString(signature.String())
	e.buf.WriteString("\n\n")
}

func (e *Emitter) emitConst(result convert.ConvertResult) {
	e.emitDocWithIndent(result.Doc, "")

	if result.ConstValue != "" {
		if e.isInferredNamedType(result.LisetteType) {
			fmt.Fprintf(&e.buf, "const %s: %s = %s\n\n", result.Name, result.LisetteType, result.ConstValue)
		} else {
			fmt.Fprintf(&e.buf, "const %s = %s\n\n", result.Name, result.ConstValue)
		}
	} else {
		fmt.Fprintf(&e.buf, "const %s: %s\n\n", result.Name, result.LisetteType)
	}
}

func (e *Emitter) isInferredNamedType(typeStr string) bool {
	basicTypes := map[string]bool{
		"bool":       true,
		"int":        true,
		"int8":       true,
		"int16":      true,
		"int32":      true,
		"int64":      true,
		"uint":       true,
		"uint8":      true,
		"uint16":     true,
		"uint32":     true,
		"uint64":     true,
		"uintptr":    true,
		"float32":    true,
		"float64":    true,
		"complex64":  true,
		"complex128": true,
		"string":     true,
		"byte":       true,
		"rune":       true,
		"error":      true,
		"Unknown":    true,
		"()":         true,
	}
	return !basicTypes[typeStr] && !strings.Contains(typeStr, "<")
}

func (e *Emitter) emitVariable(result convert.ConvertResult) {
	e.emitDocWithIndent(result.Doc, "")
	fmt.Fprintf(&e.buf, "pub var %s: %s\n\n", result.Name, result.LisetteType)
}

func (e *Emitter) EmitTypedConst(result convert.ConvertResult, typeName string) {
	e.emitDocWithIndent(result.Doc, "")
	fmt.Fprintf(&e.buf, "pub const %s: %s = %s\n\n", result.Name, typeName, result.ConstValue)
	e.stats.constants++
}

func (e *Emitter) EmitValueEnum(info convert.ValueEnumInfo) {
	var signature strings.Builder
	signature.WriteString("pub enum ")
	signature.WriteString(info.TypeName)
	if info.UnderlyingType != "" {
		signature.WriteString(": ")
		signature.WriteString(info.UnderlyingType)
	}
	signature.WriteString(" {\n")
	for _, v := range info.Variants {
		signature.WriteString("  ")
		signature.WriteString(v.Name)
		signature.WriteString(" = ")
		signature.WriteString(v.Value)
		signature.WriteString(",\n")
	}
	signature.WriteString("}")

	e.buf.WriteString(signature.String())
	e.buf.WriteString("\n\n")
	e.stats.types++
}

func (e *Emitter) emitDocWithIndent(doc, indent string) {
	if doc == "" {
		return
	}

	for line := range strings.SplitSeq(doc, "\n") {
		e.buf.WriteString(indent)
		e.buf.WriteString("/// ")
		e.buf.WriteString(line)
		e.buf.WriteString("\n")
	}
}
