package emit

import (
	"fmt"
	"slices"
	"strings"

	"github.com/ivov/lisette/bindgen/internal/config"
	"github.com/ivov/lisette/bindgen/internal/convert"
	"github.com/ivov/lisette/bindgen/internal/extract"
)

func writeSkippedFieldComment(w *strings.Builder, indent string, f convert.StructField) {
	fmt.Fprintf(w, "%s// SKIPPED field %q: %s — %s\n", indent, f.Name, f.SkipReason.Code, f.SkipReason.Message)
}

type stats struct {
	functions int
	methods   int
	types     int
	constants int
	variables int
}

type Emitter struct {
	buf        strings.Builder
	stats      stats
	skipped    int
	methods    map[string][]convert.ConvertResult // receiver type name -> methods
	cfg        *config.Config
	pkgPath    string
	pkgAliases map[string]string // package path -> local prefix used in references
}

func NewEmitter(cfg *config.Config, pkgPath string) *Emitter {
	return &Emitter{
		methods: make(map[string][]convert.ConvertResult),
		cfg:     cfg,
		pkgPath: pkgPath,
	}
}

func (e *Emitter) EmitHeader(pkg, pkgName, lisetteVersion, goVersion string) {
	e.buf.WriteString("// Generated by Lisette bindgen\n")
	fmt.Fprintf(&e.buf, "// Source: %s (%s)\n", pkg, packageSourceType(pkg))
	if lastSegment := pkg[strings.LastIndex(pkg, "/")+1:]; pkgName != lastSegment {
		fmt.Fprintf(&e.buf, "// Package: %s\n", pkgName)
	}
	fmt.Fprintf(&e.buf, "// Go: %s\n", strings.TrimPrefix(goVersion, "go"))
	fmt.Fprintf(&e.buf, "// Lisette: %s\n", lisetteVersion)
	e.buf.WriteString("\n")
}

func packageSourceType(pkg string) string {
	if strings.HasPrefix(pkg, "/") || strings.HasPrefix(pkg, "./") || strings.HasPrefix(pkg, "../") {
		return "local"
	}

	if strings.HasPrefix(pkg, "golang.org/x/") {
		return "Go extended"
	}

	firstSegment := pkg
	if idx := strings.Index(pkg, "/"); idx != -1 {
		firstSegment = pkg[:idx]
	}

	if strings.Contains(firstSegment, ".") {
		return "Go community"
	}

	return "Go stdlib"
}

func (e *Emitter) EmitImports(externalPkgs convert.ExternalPkgs) {
	if len(externalPkgs) == 0 {
		return
	}

	e.pkgAliases = computePkgAliases(externalPkgs)

	paths := make([]string, 0, len(externalPkgs))
	for path := range externalPkgs {
		paths = append(paths, path)
	}
	slices.Sort(paths)

	for _, path := range paths {
		prefix := e.pkgAliases[path]
		if prefix == externalPkgs[path] {
			fmt.Fprintf(&e.buf, "import \"go:%s\"\n", path)
		} else {
			fmt.Fprintf(&e.buf, "import %s \"go:%s\"\n", prefix, path)
		}
	}

	e.buf.WriteString("\n")
}

// computePkgAliases resolves each path to a local prefix. On a Go-declared
// name collision (e.g. `html/template` vs `text/template`) the path with
// the fewest segments keeps the bare name (lex tiebreaker); the rest get a
// synthesized alias by widening the trailing-segment window until unique
// against bare names and previously-synthesized aliases.
func computePkgAliases(externalPkgs convert.ExternalPkgs) map[string]string {
	byName := make(map[string][]string)
	for path, name := range externalPkgs {
		byName[name] = append(byName[name], path)
	}

	aliases := make(map[string]string, len(externalPkgs))
	taken := make(map[string]bool)
	pending := make([]string, 0, len(externalPkgs)-len(byName))

	for name, paths := range byName {
		slices.SortFunc(paths, compareByDepth)
		aliases[paths[0]] = name
		taken[name] = true
		pending = append(pending, paths[1:]...)
	}

	slices.SortFunc(pending, compareByDepth)
	for _, path := range pending {
		alias := aliasForPath(path, taken)
		aliases[path] = alias
		taken[alias] = true
	}

	return aliases
}

func compareByDepth(a, b string) int {
	if as, bs := strings.Count(a, "/"), strings.Count(b, "/"); as != bs {
		return as - bs
	}
	return strings.Compare(a, b)
}

func aliasForPath(path string, taken map[string]bool) string {
	parts := strings.Split(path, "/")
	if len(parts) < 2 {
		return sanitizeIdent(path)
	}
	for n := 2; n < len(parts); n++ {
		candidate := joinAndSanitize(parts[len(parts)-n:])
		if !taken[candidate] {
			return candidate
		}
	}
	return joinAndSanitize(parts)
}

func joinAndSanitize(parts []string) string {
	var b strings.Builder
	for i, p := range parts {
		if i > 0 {
			b.WriteByte('_')
		}
		b.WriteString(sanitizeIdent(p))
	}
	return b.String()
}

func sanitizeIdent(s string) string {
	var b strings.Builder
	b.Grow(len(s))
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '_':
			b.WriteRune(r)
		default:
			b.WriteRune('_')
		}
	}
	return b.String()
}

func (e *Emitter) EmitExport(result convert.ConvertResult) {
	if result.SyntheticType != nil {
		e.EmitExport(*result.SyntheticType)
	}
	switch result.Kind {
	case extract.ExportFunction:
		e.emitFunction(result)
		e.stats.functions++
	case extract.ExportMethod:
		if e.collectMethod(result) {
			e.stats.methods++
		}
	case extract.ExportType:
		e.emitType(result)
		e.stats.types++
	case extract.ExportConstant:
		e.emitConst(result)
		e.stats.constants++
	case extract.ExportVariable:
		e.emitVariable(result)
		e.stats.variables++
	}
}

func (e *Emitter) collectMethod(result convert.ConvertResult) bool {
	if result.Receiver == nil {
		return false
	}

	baseTypeName := result.Receiver.BaseTypeName
	if baseTypeName == "" {
		return false
	}

	e.methods[baseTypeName] = append(e.methods[baseTypeName], result)
	return true
}

// CollectSkippedMethod buckets a skipped method under its receiver type so
// the impl block renders a `// SKIPPED method` comment in place of the
// unrepresentable signature. Returns false when the receiver could not be
// established (in which case the caller falls back to a top-level skip).
func (e *Emitter) CollectSkippedMethod(result convert.ConvertResult) bool {
	if result.Receiver == nil || result.Receiver.BaseTypeName == "" {
		return false
	}
	e.methods[result.Receiver.BaseTypeName] = append(e.methods[result.Receiver.BaseTypeName], result)
	e.skipped++
	return true
}

func (e *Emitter) EmitUnloadableNote(firstError string) {
	e.buf.WriteString("// Status: UNLOADABLE — package could not be type-checked on this host\n")
	fmt.Fprintf(&e.buf, "// First error: %s\n", firstError)
	e.buf.WriteString("\n")
}

func (e *Emitter) EmitSkipped(result convert.ConvertResult) {
	fmt.Fprintf(&e.buf, "// SKIPPED: %s - %s\n", result.Name, result.SkipReason.Code)
	fmt.Fprintf(&e.buf, "// %s\n", result.SkipReason.Message)

	if result.SkipReason.EmitOpaqueType {
		fmt.Fprintf(&e.buf, "pub type %s%s\n", result.Name, result.TypeParams.DeclBlock())
		e.stats.types++
	}

	e.buf.WriteString("\n")
	e.skipped++
}

func (e *Emitter) EmitImplBlocks() {
	if len(e.methods) == 0 {
		return
	}

	typeNames := make([]string, 0, len(e.methods))
	for typeName := range e.methods {
		typeNames = append(typeNames, typeName)
	}
	slices.Sort(typeNames)

	for _, typeName := range typeNames {
		methods := e.methods[typeName]
		if len(methods) == 0 {
			continue
		}

		var typeParams convert.TypeParamSpecs
		if methods[0].Receiver != nil {
			typeParams = methods[0].Receiver.TypeParams
		}

		if len(typeParams) > 0 {
			fmt.Fprintf(&e.buf, "impl<%s> %s<%s> {\n", typeParams.FormatDecl(), typeName, typeParams.FormatUse())
		} else {
			fmt.Fprintf(&e.buf, "impl %s {\n", typeName)
		}
		for _, method := range methods {
			e.emitMethodInImpl(method)
		}

		e.buf.WriteString("}\n\n")
	}
}

func (e *Emitter) Summary() string {
	var buf strings.Builder
	total := e.stats.functions + e.stats.methods + e.stats.types + e.stats.constants + e.stats.variables
	fmt.Fprintf(&buf, "Generated: %d functions, %d methods, %d types, %d constants, %d variables\n",
		e.stats.functions, e.stats.methods, e.stats.types, e.stats.constants, e.stats.variables)
	fmt.Fprintf(&buf, "Total: %d symbols\n", total)
	if e.skipped > 0 {
		fmt.Fprintf(&buf, "Skipped: %d symbols\n", e.skipped)
	}
	return buf.String()
}

func (e *Emitter) String() string {
	raw := e.buf.String()
	if len(e.pkgAliases) > 0 {
		pairs := make([]string, 0, len(e.pkgAliases)*2)
		for path, prefix := range e.pkgAliases {
			pairs = append(pairs, convert.PkgRefStart+path+convert.PkgRefEnd, prefix)
		}
		raw = strings.NewReplacer(pairs...).Replace(raw)
	}
	return strings.TrimRight(raw, "\n") + "\n"
}

func (e *Emitter) emitFunction(result convert.ConvertResult) {
	e.emitDocWithIndent(result.Doc, "")

	if result.CommaOk {
		e.buf.WriteString("#[go(comma_ok)]\n")
	}
	if result.ArrayReturn {
		e.buf.WriteString("#[go(array_return)]\n")
	}
	if result.SentinelInt != nil {
		e.buf.WriteString(sentinelFlag(*result.SentinelInt) + "\n")
	}
	if e.shouldAllowUnusedResult(result.Name, "", result) {
		e.buf.WriteString("#[allow(unused_result)]\n")
	}
	if result.HasReturn() && e.cfg.ShouldAllowUnusedValue(e.pkgPath, result.Name) {
		e.buf.WriteString("#[allow(unused_value)]\n")
	}

	var functionSignature strings.Builder
	functionSignature.WriteString("pub fn ")
	functionSignature.WriteString(result.Name)

	functionSignature.WriteString(result.TypeParams.DeclBlock())
	functionSignature.WriteString("(")
	var params []string
	for _, p := range result.Params {
		if p.Mutable {
			params = append(params, fmt.Sprintf("mut %s: %s", p.Name, p.Type))
		} else {
			params = append(params, fmt.Sprintf("%s: %s", p.Name, p.Type))
		}
	}
	functionSignature.WriteString(strings.Join(params, ", "))
	functionSignature.WriteString(")")

	if result.HasReturn() {
		functionSignature.WriteString(" -> ")
		functionSignature.WriteString(result.ReturnType)
	}

	e.buf.WriteString(functionSignature.String())
	e.buf.WriteString("\n\n")
}

// shouldAllowUnusedResult returns true if the function/method should be annotated
// with #[allow(unused_result)]. Checks config first, then applies signature-based
// heuristics for common Go interface methods:
//   - Close() error
//   - Flush() error
//   - Write([]byte) (int, error)  [io.Writer signature]
func (e *Emitter) shouldAllowUnusedResult(qualifiedName, methodName string, result convert.ConvertResult) bool {
	if e.cfg != nil && e.cfg.ShouldAllowUnusedResult(e.pkgPath, qualifiedName) {
		return true
	}

	name := methodName
	if name == "" {
		name = result.Name
	}

	switch name {
	case "Close", "Flush":
		return len(result.Params) == 0 && result.ReturnType == "Result<(), error>"
	case "Write":
		return len(result.Params) == 1 &&
			(result.Params[0].Type == "Slice<byte>" || result.Params[0].Type == "Slice<uint8>") &&
			result.ReturnType == "Result<int, error>"
	}

	return false
}

func (e *Emitter) emitMethodInImpl(result convert.ConvertResult) {
	if result.SkipReason != nil {
		fmt.Fprintf(&e.buf, "  // SKIPPED method %q: %s — %s\n", result.Name, result.SkipReason.Code, result.SkipReason.Message)
		return
	}

	e.emitDocWithIndent(result.Doc, "  ")

	if result.CommaOk {
		e.buf.WriteString("  #[go(comma_ok)]\n")
	}
	if result.ArrayReturn {
		e.buf.WriteString("  #[go(array_return)]\n")
	}
	if result.SentinelInt != nil {
		e.buf.WriteString("  " + sentinelFlag(*result.SentinelInt) + "\n")
	}
	if result.Receiver != nil {
		qualifiedName := result.Receiver.BaseTypeName + "." + result.Name
		if e.shouldAllowUnusedResult(qualifiedName, result.Name, result) {
			e.buf.WriteString("  #[allow(unused_result)]\n")
		}
	}
	if result.BuilderMethod {
		e.buf.WriteString("  #[allow(unused_value)]\n")
	}

	var methodSignature strings.Builder
	methodSignature.WriteString("  fn ")
	methodSignature.WriteString(result.Name)

	methodSignature.WriteString(result.TypeParams.DeclBlock())
	methodSignature.WriteString("(")
	var params []string
	if result.Receiver != nil && result.Receiver.IsPointer {
		typeName := result.Receiver.BaseTypeName + result.Receiver.TypeParams.UseBlock()
		params = append(params, fmt.Sprintf("self: Ref<%s>", typeName))
	} else {
		params = append(params, "self")
	}

	for _, p := range result.Params {
		if p.Mutable {
			params = append(params, fmt.Sprintf("mut %s: %s", p.Name, p.Type))
		} else {
			params = append(params, fmt.Sprintf("%s: %s", p.Name, p.Type))
		}
	}

	methodSignature.WriteString(strings.Join(params, ", "))
	methodSignature.WriteString(")")

	if result.HasReturn() {
		methodSignature.WriteString(" -> ")
		methodSignature.WriteString(result.ReturnType)
	}

	e.buf.WriteString(methodSignature.String())
	e.buf.WriteString("\n")
}

func (e *Emitter) emitType(result convert.ConvertResult) {
	e.emitDocWithIndent(result.Doc, "")

	typeName := result.Name

	if result.IsInterface {
		var signature strings.Builder
		signature.WriteString("pub interface ")
		signature.WriteString(typeName)
		signature.WriteString(result.TypeParams.DeclBlock())

		if len(result.InterfaceMethods) == 0 {
			signature.WriteString(" {}")
		} else {
			signature.WriteString(" {\n")
			for _, m := range result.InterfaceMethods {
				if m.CommaOk {
					signature.WriteString("  #[go(comma_ok)]\n")
				}
				if m.ArrayReturn {
					signature.WriteString("  #[go(array_return)]\n")
				}
				signature.WriteString("  fn ")
				signature.WriteString(m.Name)
				signature.WriteString("(")

				var params []string
				for _, p := range m.Params {
					if p.Mutable {
						params = append(params, fmt.Sprintf("mut %s: %s", p.Name, p.Type))
					} else {
						params = append(params, fmt.Sprintf("%s: %s", p.Name, p.Type))
					}
				}
				signature.WriteString(strings.Join(params, ", "))
				signature.WriteString(")")

				if m.HasReturn() {
					signature.WriteString(" -> ")
					signature.WriteString(m.ReturnType)
				}
				signature.WriteString("\n")
			}
			signature.WriteString("}")
		}

		e.buf.WriteString(signature.String())
		e.buf.WriteString("\n\n")
		return
	}

	if len(result.Fields) > 0 {
		allSkipped := true
		for _, f := range result.Fields {
			if f.SkipReason == nil {
				allSkipped = false
				break
			}
		}

		if allSkipped {
			for _, f := range result.Fields {
				writeSkippedFieldComment(&e.buf, "", f)
			}
			fmt.Fprintf(&e.buf, "pub type %s%s\n\n", typeName, result.TypeParams.DeclBlock())
			return
		}

		var sig strings.Builder
		sig.WriteString("pub struct ")
		sig.WriteString(typeName)
		sig.WriteString(result.TypeParams.DeclBlock())

		sig.WriteString(" {\n")
		for _, f := range result.Fields {
			if f.SkipReason != nil {
				writeSkippedFieldComment(&sig, "  ", f)
				continue
			}
			if f.Doc != "" {
				for line := range strings.SplitSeq(f.Doc, "\n") {
					sig.WriteString("  /// ")
					sig.WriteString(line)
					sig.WriteString("\n")
				}
			}
			sig.WriteString("  pub ")
			sig.WriteString(f.Name)
			sig.WriteString(": ")
			sig.WriteString(f.Type)
			sig.WriteString(",\n")
		}
		sig.WriteString("}")

		e.buf.WriteString(sig.String())
		e.buf.WriteString("\n\n")
		return
	}

	if result.LisetteType != "" {
		var sig strings.Builder

		// Lisette rejects self-referential type aliases, so a Go function-type
		// like `type Filter func([]Filter)` falls back to an opaque type;
		// downstream signatures referencing it still resolve.
		isFnType := strings.HasPrefix(result.LisetteType, "fn(")
		isRecursiveFnAlias := isFnType && containsIdent(result.LisetteType, typeName)

		if isRecursiveFnAlias {
			sig.WriteString("pub type ")
			sig.WriteString(typeName)
			sig.WriteString(result.TypeParams.DeclBlock())
		} else if isFnType || result.IsTypeAlias {
			sig.WriteString("pub type ")
			sig.WriteString(typeName)
			sig.WriteString(result.TypeParams.DeclBlock())
			sig.WriteString(" = ")
			sig.WriteString(result.LisetteType)
		} else {
			sig.WriteString("pub struct ")
			sig.WriteString(typeName)
			sig.WriteString(result.TypeParams.DeclBlock())
			sig.WriteString("(")
			sig.WriteString(result.LisetteType)
			sig.WriteString(")")
		}

		e.buf.WriteString(sig.String())
		e.buf.WriteString("\n\n")
		return
	}

	var signature strings.Builder
	signature.WriteString("pub type ")
	signature.WriteString(typeName)
	signature.WriteString(result.TypeParams.DeclBlock())

	e.buf.WriteString(signature.String())
	e.buf.WriteString("\n\n")
}

func (e *Emitter) emitConst(result convert.ConvertResult) {
	e.emitDocWithIndent(result.Doc, "")

	if result.ConstValue != "" {
		if e.isInferredNamedType(result.LisetteType) {
			fmt.Fprintf(&e.buf, "pub const %s: %s = %s\n\n", result.Name, result.LisetteType, result.ConstValue)
		} else {
			fmt.Fprintf(&e.buf, "pub const %s = %s\n\n", result.Name, result.ConstValue)
		}
	} else {
		fmt.Fprintf(&e.buf, "pub const %s: %s\n\n", result.Name, result.LisetteType)
	}
}

func (e *Emitter) isInferredNamedType(typeStr string) bool {
	basicTypes := map[string]bool{
		"bool":       true,
		"int":        true,
		"int8":       true,
		"int16":      true,
		"int32":      true,
		"int64":      true,
		"uint":       true,
		"uint8":      true,
		"uint16":     true,
		"uint32":     true,
		"uint64":     true,
		"uintptr":    true,
		"float32":    true,
		"float64":    true,
		"complex64":  true,
		"complex128": true,
		"string":     true,
		"byte":       true,
		"rune":       true,
		"error":      true,
		"Unknown":    true,
		"()":         true,
	}
	return !basicTypes[typeStr] && !strings.Contains(typeStr, "<")
}

func (e *Emitter) emitVariable(result convert.ConvertResult) {
	e.emitDocWithIndent(result.Doc, "")
	fmt.Fprintf(&e.buf, "pub var %s: %s\n\n", result.Name, result.LisetteType)
}

func (e *Emitter) EmitTypedConst(result convert.ConvertResult, typeName string) {
	e.emitDocWithIndent(result.Doc, "")
	fmt.Fprintf(&e.buf, "pub const %s: %s = %s\n\n", result.Name, typeName, result.ConstValue)
	e.stats.constants++
}

func (e *Emitter) EmitValueEnum(info convert.ValueEnumInfo) {
	var signature strings.Builder
	signature.WriteString("pub enum ")
	signature.WriteString(info.TypeName)
	if info.UnderlyingType != "" {
		signature.WriteString(": ")
		signature.WriteString(info.UnderlyingType)
	}
	signature.WriteString(" {\n")
	for _, v := range info.Variants {
		signature.WriteString("  ")
		signature.WriteString(v.Name)
		signature.WriteString(" = ")
		signature.WriteString(v.Value)
		signature.WriteString(",\n")
	}
	signature.WriteString("}")

	e.buf.WriteString(signature.String())
	e.buf.WriteString("\n\n")
	e.stats.types++
}

func (e *Emitter) emitDocWithIndent(doc, indent string) {
	if doc == "" {
		return
	}

	for line := range strings.SplitSeq(doc, "\n") {
		e.buf.WriteString(indent)
		e.buf.WriteString("/// ")
		e.buf.WriteString(line)
		e.buf.WriteString("\n")
	}
}

func sentinelFlag(value int) string {
	switch value {
	case -1:
		return "#[go(sentinel_minus_one)]"
	}
	panic(fmt.Sprintf("bindgen: unsupported sentinel value %d (add a flag mapping)", value))
}

// containsIdent reports whether name appears in s as a standalone identifier.
func containsIdent(s, name string) bool {
	if name == "" {
		return false
	}
	for i := 0; ; {
		rel := strings.Index(s[i:], name)
		if rel < 0 {
			return false
		}
		idx := i + rel
		end := idx + len(name)
		var before, after byte
		if idx > 0 {
			before = s[idx-1]
		}
		if end < len(s) {
			after = s[end]
		}
		if !isIdentByte(before) && !isIdentByte(after) {
			return true
		}
		i = idx + 1
	}
}

func isIdentByte(b byte) bool {
	return b == '_' ||
		(b >= 'a' && b <= 'z') ||
		(b >= 'A' && b <= 'Z') ||
		(b >= '0' && b <= '9')
}
