alias b := build
alias c := check
alias t := test
alias tr := test-review
alias ta := test-accept
alias te := test-e2e-smoke
alias r := run
alias f := format
alias l := lint
alias lf := lintfix
alias cov := test-cov


build:
    cargo build --release

build-debug:
    cargo build

test:
    cargo test -p tests --test suite
    cargo test -p tests --test lsp

test-infer:
    cargo test -p tests --test suite infer_tests

test-watch:
    cargo watch -x "test -p tests --test suite"

test-review:
    cargo insta review

test-accept:
    cargo insta accept --all

test-e2e-smoke:
    cargo test -p tests --test suite e2e_smoke

test-e2e-suite:
    cargo test -p tests --test e2e_suite -- --nocapture

test-cov:
    cargo llvm-cov -p tests --test suite --test lsp --html --open

test-refresh-snapshots:
    cargo insta test --force-update-snapshots

format:
    cargo fmt

format-check:
    cargo fmt -- --check

lint:
    cargo clippy --all-targets -- -D warnings

lintfix:
    cargo clippy --fix --allow-dirty --allow-staged

run file:
    cargo run -p lisette -- {{file}}

check: format-check test lint

perf-flamegraph:
    cargo build --profile flamegraph -p lisette
    sudo flamegraph -o flamegraph.svg -- ./target/flamegraph/lis check tests/e2e_smoke_project/src/main.lis

perf-samply:
    cargo build --profile flamegraph -p lisette
    samply record ./target/flamegraph/lis check tests/e2e_smoke_project/src/main.lis

fuzz-parse duration="300":
    cargo +nightly fuzz run parse --sanitizer address -- -max_total_time={{duration}} -rss_limit_mb=2048 -dict=fuzz/lisette.dict

fuzz-infer duration="300":
    cargo +nightly fuzz run infer --sanitizer address -- -max_total_time={{duration}} -rss_limit_mb=2048 -dict=fuzz/lisette.dict

generate-stdlib-typedefs version:
    cd bindgen && just build
    just build # make binary to run bindgen
    ./target/release/lis bindgen stdlib {{version}}
    ./target/release/lis format crates/stdlib/typedefs/
    just build # recompile compiler to embed updated typedefs
    ./target/release/lis check crates/stdlib/typedefs/
    just format

commit-stdlib-typedefs version:
    git add crates/stdlib/
    LEFTHOOK=0 git commit -m "chore: bump stdlib typedefs to v{{version}}"

_stdlib-typedef-version:
    @grep '// Lisette:' crates/stdlib/typedefs/fmt.d.lis | awk '{print $3}'

check-stdlib-drift:
    just generate-stdlib-typedefs "$(just _stdlib-typedef-version)"
    git diff --exit-code crates/stdlib/

# Build the playground and write output to docs/play/ (served at lisette.run/play)
rebuild-playground:
    cd playground && npm install && npm run build:wasm && npm run build

# release.yml is autogenerated by cargo-dist; ratchet must not modify it
_ratchet cmd:
    find .github/workflows .github/actions -name '*.yml' -not -name release.yml -exec ratchet {{cmd}} {} +

ci-pin: (_ratchet "pin")

ci-update: (_ratchet "update")

ci-upgrade: (_ratchet "upgrade")

ci-lint: (_ratchet "lint")
