[workspace]
changelog_update = false
git_tag_enable = false
git_release_enable = false
semver_check = false

[[package]]
name = "lisette"
git_tag_enable = true
git_release_enable = true
changelog_update = true
changelog_path = "./CHANGELOG.md"
changelog_include = [
  "lisette-syntax",
  "lisette-semantics",
  "lisette-diagnostics",
  "lisette-emit",
  "lisette-format",
  "lisette-stdlib",
  "lisette-lsp",
]

[changelog]
header = """# Changelog

Lisette is under active development. Any version before 1.0.0 may include breaking changes.
"""
