package cli

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"slices"
	"strings"
	"sync/atomic"
	"time"

	"github.com/ivov/lisette/bindgen/internal/config"
	"github.com/ivov/lisette/bindgen/internal/extract"
	"golang.org/x/sync/errgroup"
	"golang.org/x/tools/go/packages"
)

type GenerateStdResult struct {
	Generated int
	Skipped   int
	Duration  time.Duration
}

const rustIndexFileTemplate = `// Generated by Lisette bindgen. DO NOT EDIT.

use std::collections::HashMap;
use std::sync::LazyLock;

use crate::Target;

static GO_STDLIB_TYPEDEFS: LazyLock<HashMap<&str, &str>> = LazyLock::new(|| {
    HashMap::from([
%s    ])
});

pub fn get_go_stdlib_typedef(package: &str, _target: Target) -> Option<&'static str> {
    GO_STDLIB_TYPEDEFS.get(package).copied()
}

pub fn get_go_stdlib_packages(_target: Target) -> Vec<&'static str> {
    let mut packages: Vec<&'static str> = GO_STDLIB_TYPEDEFS.keys().copied().collect();
    packages.sort();
    packages
}
`

// GenerateStd generates `.d.lis` files for all Go std packages.
func GenerateStd(ctx context.Context, outDir, lisetteVersion, goVersion string, cfg *config.Config) (GenerateStdResult, error) {
	start := time.Now()

	pkgPaths, err := listStdlibPackages()
	if err != nil {
		return GenerateStdResult{}, fmt.Errorf("failed to list stdlib packages: %w", err)
	}

	loadStart := time.Now()

	pkgs, err := extract.LoadPackages(pkgPaths)
	if err != nil {
		return GenerateStdResult{}, fmt.Errorf("failed to load packages: %w", err)
	}

	fmt.Fprintf(os.Stderr, "Loaded %d packages in %.1fs\n\n", len(pkgs), time.Since(loadStart).Seconds())

	dirs := make(map[string]struct{})
	for _, pkg := range pkgs {
		dir := filepath.Dir(filepath.Join(outDir, pkg.PkgPath))
		dirs[dir] = struct{}{}
	}
	for dir := range dirs {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return GenerateStdResult{}, fmt.Errorf("failed to create directory %s: %w", dir, err)
		}
	}

	var generated atomic.Int32
	total := len(pkgs)

	g, ctx := errgroup.WithContext(ctx)
	g.SetLimit(runtime.NumCPU())

	for _, pkg := range pkgs {
		g.Go(func() error {
			select {
			case <-ctx.Done():
				return ctx.Err()
			default:
			}

			result := generateFromPackage(pkg, pkg.PkgPath, lisetteVersion, goVersion, cfg)

			outPath := filepath.Join(outDir, pkg.PkgPath+".d.lis")

			if err := os.WriteFile(outPath, []byte(result.Content), 0644); err != nil {
				return fmt.Errorf("failed to write %s: %w", outPath, err)
			}

			n := generated.Add(1)
			fmt.Fprintf(os.Stderr, "[%3d/%d] %s\n", n, total, pkg.PkgPath)

			return nil
		})
	}

	if err := g.Wait(); err != nil {
		return GenerateStdResult{}, err
	}

	if err := generateRustIndexFile(outDir, pkgs); err != nil {
		return GenerateStdResult{}, fmt.Errorf("failed to generate Rust index file: %w", err)
	}

	skipped := len(pkgPaths) - len(pkgs)

	return GenerateStdResult{
		Generated: int(generated.Load()),
		Skipped:   skipped,
		Duration:  time.Since(start),
	}, nil
}

func listStdlibPackages() ([]string, error) {
	cmd := exec.Command("go", "list", "std")
	out, err := cmd.Output()
	if err != nil {
		return nil, err
	}

	var pkgs []string
	for line := range strings.SplitSeq(strings.TrimSpace(string(out)), "\n") {
		if shouldSkipPackage(line) {
			continue
		}
		pkgs = append(pkgs, line)
	}

	return pkgs, nil
}

func shouldSkipPackage(pkg string) bool {
	return strings.Contains(pkg, "/internal") ||
		strings.HasPrefix(pkg, "internal/") ||
		strings.Contains(pkg, "/vendor/") ||
		strings.HasPrefix(pkg, "vendor/") ||
		strings.HasSuffix(pkg, "_test")
}

func generateRustIndexFile(outDir string, pkgs []*packages.Package) error {
	srcDir := filepath.Join(outDir, "..", "src")
	if _, err := os.Stat(srcDir); os.IsNotExist(err) {
		return nil
	}

	paths := make([]string, 0, len(pkgs))
	for _, pkg := range pkgs {
		paths = append(paths, pkg.PkgPath)
	}
	slices.Sort(paths)

	var entries strings.Builder
	for _, pkgPath := range paths {
		entries.WriteString(fmt.Sprintf(
			"        (%q, include_str!(\"../typedefs/%s.d.lis\")),\n",
			pkgPath, pkgPath,
		))
	}

	content := fmt.Sprintf(rustIndexFileTemplate, entries.String())

	rustFilePath := filepath.Join(srcDir, "go_modules.rs")
	if err := os.WriteFile(rustFilePath, []byte(content), 0644); err != nil {
		return err
	}

	fmt.Fprintf(os.Stderr, "\nGenerated: %s\n", rustFilePath)
	return nil
}
