package cli

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"slices"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/ivov/lisette/bindgen/internal/config"
	"github.com/ivov/lisette/bindgen/internal/extract"
	"golang.org/x/sync/errgroup"
)

type GenerateStdResult struct {
	Generated int
	Duration  time.Duration
}

type Target struct {
	GOOS, GOARCH string
}

func (t Target) String() string {
	return t.GOOS + "/" + t.GOARCH
}

func (t Target) Suffix() string {
	return t.GOOS + "_" + t.GOARCH
}

const rustIndexFileTemplate = `// Generated by Lisette bindgen. DO NOT EDIT.

use std::collections::HashMap;
use std::sync::LazyLock;

use crate::Target;

static GO_STDLIB_COMMON: LazyLock<HashMap<&str, &str>> = LazyLock::new(|| {
    HashMap::from([
%s    ])
});

%s
static GO_STDLIB_PACKAGE_TARGETS: LazyLock<HashMap<&str, &[(&str, &str)]>> =
    LazyLock::new(|| {
        HashMap::from([
%s        ])
    });

pub fn get_go_stdlib_typedef(package: &str, target: Target) -> Option<&'static str> {
    if !is_available_on(package, target) {
        return None;
    }
    if let Some(source) = lookup_in_overlay(target, package) {
        return Some(source);
    }
    GO_STDLIB_COMMON.get(package).copied()
}

pub fn get_go_stdlib_packages(target: Target) -> Vec<&'static str> {
    let mut packages: Vec<&'static str> = GO_STDLIB_COMMON
        .keys()
        .copied()
        .filter(|pkg| is_available_on(pkg, target))
        .collect();
    if let Some(overlay) = overlay_for(target) {
        packages.extend(overlay.keys().copied());
    }
    packages.sort();
    packages
}

pub fn get_go_stdlib_package_targets(
    package: &str,
) -> Option<&'static [(&'static str, &'static str)]> {
    GO_STDLIB_PACKAGE_TARGETS.get(package).copied()
}

fn is_available_on(package: &str, target: Target) -> bool {
    match GO_STDLIB_PACKAGE_TARGETS.get(package) {
        Some(targets) => targets
            .iter()
            .any(|(goos, goarch)| *goos == target.goos && *goarch == target.goarch),
        None => true,
    }
}

fn lookup_in_overlay(target: Target, package: &str) -> Option<&'static str> {
    overlay_for(target).and_then(|overlay| overlay.get(package).copied())
}

fn overlay_for(target: Target) -> Option<&'static HashMap<&'static str, &'static str>> {
    match (target.goos, target.goarch) {
%s        _ => None,
    }
}
`

// GenerateStd generates per-target `.d.lis` files and deduplicates them
// into a suffixless shared layer plus per-target overlays.
func GenerateStd(ctx context.Context, outDir, lisetteVersion, goVersion string, cfg *config.Config, targets []Target) (GenerateStdResult, error) {
	start := time.Now()

	if len(targets) < 2 {
		return GenerateStdResult{}, fmt.Errorf("at least two targets are required: a single-target regen cannot distinguish platform-conditional packages from common ones")
	}

	prevGOOS, hadGOOS := os.LookupEnv("BINDGEN_TARGET_GOOS")
	prevGOARCH, hadGOARCH := os.LookupEnv("BINDGEN_TARGET_GOARCH")
	defer func() {
		restoreEnv("BINDGEN_TARGET_GOOS", prevGOOS, hadGOOS)
		restoreEnv("BINDGEN_TARGET_GOARCH", prevGOARCH, hadGOARCH)
	}()

	captured := make(map[Target]map[string]string)

	for _, target := range targets {
		fmt.Fprintf(os.Stderr, "\n=== Target %s ===\n", target)

		if err := os.Setenv("BINDGEN_TARGET_GOOS", target.GOOS); err != nil {
			return GenerateStdResult{}, fmt.Errorf("setenv BINDGEN_TARGET_GOOS: %w", err)
		}
		if err := os.Setenv("BINDGEN_TARGET_GOARCH", target.GOARCH); err != nil {
			return GenerateStdResult{}, fmt.Errorf("setenv BINDGEN_TARGET_GOARCH: %w", err)
		}

		pkgPaths, err := listStdlibPackages(target)
		if err != nil {
			return GenerateStdResult{}, fmt.Errorf("target %s: failed to list stdlib packages: %w", target, err)
		}

		loadStart := time.Now()
		pkgs, err := extract.LoadPackages(pkgPaths)
		if err != nil {
			return GenerateStdResult{}, fmt.Errorf("target %s: failed to load packages: %w", target, err)
		}
		fmt.Fprintf(os.Stderr, "Loaded %d packages in %.1fs\n\n", len(pkgs), time.Since(loadStart).Seconds())

		var generated atomic.Int32
		total := len(pkgs)

		results := make(map[string]string, len(pkgs))
		var resultsMu sync.Mutex

		g, gctx := errgroup.WithContext(ctx)
		g.SetLimit(runtime.NumCPU())

		for _, pkg := range pkgs {
			g.Go(func() error {
				select {
				case <-gctx.Done():
					return gctx.Err()
				default:
				}

				result := generateFromPackage(pkg, pkg.PkgPath, lisetteVersion, goVersion, cfg)

				resultsMu.Lock()
				results[pkg.PkgPath] = result.Content
				resultsMu.Unlock()

				n := generated.Add(1)
				fmt.Fprintf(os.Stderr, "[%3d/%d] %s\n", n, total, pkg.PkgPath)

				return nil
			})
		}

		if err := g.Wait(); err != nil {
			return GenerateStdResult{}, err
		}

		captured[target] = results
	}

	partition := partitionByTarget(captured, targets)

	if err := writeDedupedTypedefs(outDir, partition); err != nil {
		return GenerateStdResult{}, fmt.Errorf("dedup step: %w", err)
	}

	if err := generateRustIndexFile(outDir, partition, targets); err != nil {
		return GenerateStdResult{}, fmt.Errorf("failed to generate Rust index file: %w", err)
	}

	totalGenerated := 0
	for _, pkgs := range captured {
		totalGenerated += len(pkgs)
	}

	return GenerateStdResult{
		Generated: totalGenerated,
		Duration:  time.Since(start),
	}, nil
}

func restoreEnv(key, prev string, had bool) {
	if had {
		_ = os.Setenv(key, prev)
	} else {
		_ = os.Unsetenv(key)
	}
}

// variant groups targets that share byte-identical content for one package.
// The canonical target supplies the filename and is the lex-first target in
// the group per `targets` iteration order.
type variant struct {
	canonical Target
	targets   []Target
	content   string
}

type partitioned struct {
	common          map[string]string    // pkgPath -> shared content
	variants        map[string][]variant // pkgPath -> per-content variants (divergent only)
	intendedTargets map[string][]Target  // pkgPath -> targets where it is available
}

// partitionByTarget classifies packages as common (suffixless, byte-identical
// across every target where present) or divergent (one variant per content
// equivalence class). Header-only outputs are dropped — they signal a
// build-tag stub like `log/syslog` on windows. Lookup gates by
// `intendedTargets` before falling through, so a shared file is never
// returned for an unsupported target.
func partitionByTarget(captured map[Target]map[string]string, targets []Target) partitioned {
	hasRealContent := make(map[string]bool)
	for _, results := range captured {
		for pkgPath, content := range results {
			if !isHeaderOnly(content) {
				hasRealContent[pkgPath] = true
			}
		}
	}
	for _, results := range captured {
		for pkgPath, content := range results {
			if isHeaderOnly(content) && hasRealContent[pkgPath] {
				delete(results, pkgPath)
			}
		}
	}

	allPkgs := make(map[string]struct{})
	for _, results := range captured {
		for pkgPath := range results {
			allPkgs[pkgPath] = struct{}{}
		}
	}

	result := partitioned{
		common:          make(map[string]string),
		variants:        make(map[string][]variant),
		intendedTargets: make(map[string][]Target),
	}

	for pkgPath := range allPkgs {
		var presentTargets []Target
		var groups []*variant
		for _, target := range targets {
			content, ok := captured[target][pkgPath]
			if !ok {
				continue
			}
			presentTargets = append(presentTargets, target)

			placed := false
			for _, g := range groups {
				if g.content == content {
					g.targets = append(g.targets, target)
					placed = true
					break
				}
			}
			if !placed {
				groups = append(groups, &variant{
					canonical: target,
					targets:   []Target{target},
					content:   content,
				})
			}
		}

		if len(presentTargets) < len(targets) {
			result.intendedTargets[pkgPath] = presentTargets
		}

		if len(groups) == 1 {
			result.common[pkgPath] = groups[0].content
			continue
		}

		variants := make([]variant, len(groups))
		for i, g := range groups {
			variants[i] = *g
		}
		result.variants[pkgPath] = variants
	}

	return result
}

// listStdlibPackages runs `go list std` per target so the list reflects
// platform-conditional packages like `plugin` (absent on windows).
func listStdlibPackages(target Target) ([]string, error) {
	cmd := exec.Command("go", "list", "std")
	cmd.Env = append(os.Environ(),
		"GOOS="+target.GOOS,
		"GOARCH="+target.GOARCH,
		"CGO_ENABLED=0",
	)
	out, err := cmd.Output()
	if err != nil {
		return nil, err
	}

	var pkgs []string
	for line := range strings.SplitSeq(strings.TrimSpace(string(out)), "\n") {
		if shouldSkipPackage(line) {
			continue
		}
		pkgs = append(pkgs, line)
	}

	return pkgs, nil
}

func shouldSkipPackage(pkg string) bool {
	return strings.Contains(pkg, "/internal") ||
		strings.HasPrefix(pkg, "internal/") ||
		strings.Contains(pkg, "/vendor/") ||
		strings.HasPrefix(pkg, "vendor/") ||
		strings.HasSuffix(pkg, "_test")
}

// writeDedupedTypedefs writes the partitioned outputs and removes stale
// files from prior runs. Each divergent package emits one file per content
// variant, named after the variant's canonical target.
func writeDedupedTypedefs(outDir string, partition partitioned) error {
	written := make(map[string]struct{})

	write := func(outPath, content string) error {
		if err := os.MkdirAll(filepath.Dir(outPath), 0755); err != nil {
			return fmt.Errorf("mkdir %s: %w", filepath.Dir(outPath), err)
		}
		if err := os.WriteFile(outPath, []byte(content), 0644); err != nil {
			return fmt.Errorf("write %s: %w", outPath, err)
		}
		written[outPath] = struct{}{}
		return nil
	}

	for pkgPath, content := range partition.common {
		if err := write(filepath.Join(outDir, pkgPath+".d.lis"), content); err != nil {
			return err
		}
	}

	for pkgPath, variants := range partition.variants {
		for _, v := range variants {
			if err := write(filepath.Join(outDir, suffixedPath(pkgPath, v.canonical)), v.content); err != nil {
				return err
			}
		}
	}

	if err := removeStaleTypedefs(outDir, written); err != nil {
		return fmt.Errorf("remove stale: %w", err)
	}

	return nil
}

// suffixedPath converts "os/user" + linux/amd64 into "os/user_linux_amd64.d.lis".
// The suffix attaches to the basename, never to a directory segment.
func suffixedPath(pkgPath string, target Target) string {
	dir, base := filepath.Split(pkgPath)
	return filepath.Join(dir, base+"_"+target.Suffix()+".d.lis")
}

func removeStaleTypedefs(outDir string, kept map[string]struct{}) error {
	return filepath.Walk(outDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			return nil
		}
		if !strings.HasSuffix(path, ".d.lis") {
			return nil
		}
		if _, ok := kept[path]; ok {
			return nil
		}
		return os.Remove(path)
	})
}

func generateRustIndexFile(outDir string, partition partitioned, targets []Target) error {
	srcDir := filepath.Join(outDir, "..", "src")
	if _, err := os.Stat(srcDir); os.IsNotExist(err) {
		return nil
	}

	commonPaths := sortedKeys(partition.common)
	commonEntries := buildEntries(commonPaths, nil)

	// Invert variants into per-target entries pointing at canonical files.
	perTarget := make(map[Target]map[string]Target)
	for pkgPath, variants := range partition.variants {
		for _, v := range variants {
			for _, t := range v.targets {
				if perTarget[t] == nil {
					perTarget[t] = make(map[string]Target)
				}
				perTarget[t][pkgPath] = v.canonical
			}
		}
	}

	var overlayBlocks strings.Builder
	var matchArms strings.Builder
	for _, target := range targets {
		entries := perTarget[target]
		if len(entries) == 0 {
			continue
		}
		paths := make([]string, 0, len(entries))
		for p := range entries {
			paths = append(paths, p)
		}
		slices.Sort(paths)
		staticName := overlayStaticName(target)
		fmt.Fprintf(&overlayBlocks, "static %s: LazyLock<HashMap<&str, &str>> = LazyLock::new(|| {\n    HashMap::from([\n", staticName)
		overlayBlocks.WriteString(buildEntries(paths, entries))
		overlayBlocks.WriteString("    ])\n});\n\n")

		fmt.Fprintf(&matchArms, "        (%q, %q) => Some(&%s),\n", target.GOOS, target.GOARCH, staticName)
	}

	intendedEntries := buildIntendedEntries(partition.intendedTargets)

	content := fmt.Sprintf(rustIndexFileTemplate,
		commonEntries,
		overlayBlocks.String(),
		intendedEntries,
		matchArms.String(),
	)

	rustFilePath := filepath.Join(srcDir, "go_modules.rs")
	if err := os.WriteFile(rustFilePath, []byte(content), 0644); err != nil {
		return err
	}

	fmt.Fprintf(os.Stderr, "\nGenerated: %s\n", rustFilePath)
	return nil
}

func isHeaderOnly(content string) bool {
	for line := range strings.SplitSeq(content, "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "//") {
			continue
		}
		return false
	}
	return true
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	slices.Sort(keys)
	return keys
}

// buildEntries renders HashMap entries for a typedef map. When `canonical`
// is nil, paths point at suffixless files (the common map). Otherwise each
// entry points at the canonical target's file for that package.
func buildEntries(pkgPaths []string, canonical map[string]Target) string {
	var b strings.Builder
	for _, pkgPath := range pkgPaths {
		suffix := ""
		if t, ok := canonical[pkgPath]; ok {
			suffix = "_" + t.Suffix()
		}
		b.WriteString(fmt.Sprintf(
			"        (%q, include_str!(\"../typedefs/%s%s.d.lis\")),\n",
			pkgPath, pkgPath, suffix,
		))
	}
	return b.String()
}

func buildIntendedEntries(intended map[string][]Target) string {
	pkgs := make([]string, 0, len(intended))
	for pkg := range intended {
		pkgs = append(pkgs, pkg)
	}
	slices.Sort(pkgs)

	var b strings.Builder
	for _, pkg := range pkgs {
		var pairs strings.Builder
		for i, t := range intended[pkg] {
			if i > 0 {
				pairs.WriteString(", ")
			}
			fmt.Fprintf(&pairs, "(%q, %q)", t.GOOS, t.GOARCH)
		}
		b.WriteString(fmt.Sprintf("            (%q, &[%s][..]),\n", pkg, pairs.String()))
	}
	return b.String()
}

func overlayStaticName(target Target) string {
	return "GO_STDLIB_" + strings.ToUpper(target.GOOS) + "_" + strings.ToUpper(target.GOARCH)
}

func ParseTargets(s string) ([]Target, error) {
	if s == "" {
		return nil, fmt.Errorf("empty target list")
	}
	var targets []Target
	for _, part := range strings.Split(s, ",") {
		part = strings.TrimSpace(part)
		slash := strings.Index(part, "/")
		if slash < 0 {
			return nil, fmt.Errorf("target %q: expected GOOS/GOARCH", part)
		}
		targets = append(targets, Target{
			GOOS:   part[:slash],
			GOARCH: part[slash+1:],
		})
	}
	return targets, nil
}
